# Generated by Django 5.2 on 2025-08-22 17:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_backupprofile_delete_backupprofileimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='backupprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='backup_profile', to=settings.AUTH_USER_MODEL),
        ),
    ]
